name: contexts demo
on: [push]

jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: print github info
        run: |
          echo "${{ toJson(github) }}"
          echo "${{ github.ref_name }}"